#!/bin/bash

LAUNCHER_VERSION=v5.6.11
MINECRAFT_VERSION=1.21.4
FABRIC_LOADER_VERSION=0.16.10
AUTHLIB_VERSION=6

docker build --no-cache --network=host --build-arg MINECRAFT_VERSION=$MINECRAFT_VERSION --build-arg FABRIC_LOADER_VERSION=$FABRIC_LOADER_VERSION --build-arg LAUNCHER_VERSION=$LAUNCHER_VERSION --build-arg AUTHLIB_VERSION=$AUTHLIB_VERSION -t serverwrapper-fabric:$MINECRAFT_VERSION-$LAUNCHER_VERSION .
