#!/bin/bash

LAUNCHER_VERSION=v5.6.11
CLEANROOM_VERSION=0.3.1-alpha

docker build --build-arg CLEANROOM_VERSION=$CLEANROOM_VERSION --build-arg LAUNCHER_VERSION=$LAUNCHER_VERSION -t serverwrapper-cleanroom:$CLEANROOM_VERSION-$LAUNCHER_VERSION .
