#!/bin/bash

LAUNCHER_VERSION=v5.6.11
MINECRAFT_VERSION=1.21.4
AUTHLIB_VERSION=6

docker build --no-cache --network=host --build-arg MINECRAFT_VERSION=$MINECRAFT_VERSION --build-arg LAUNCHER_VERSION=$LAUNCHER_VERSION --build-arg AUTHLIB_VERSION=$AUTHLIB_VERSION -t serverwrapper-paper:$MINECRAFT_VERSION-$LAUNCHER_VERSION .
